services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "5432:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      timeout: 20s
      retries: 30
      start_interval: 1s
      interval: 2s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./server
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
