// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"go-template/internal/app/config"
	"go-template/internal/app/container"
	"go-template/pkg/database"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	engine := provideGinEngine()
	configConfig := config.New()
	dbConfig := config.NewDBConfig()
	db, err := database.New(dbConfig)
	if err != nil {
		return nil, err
	}
	app := container.NewApp(engine, configConfig, db)
	return app, nil
}

// wire.go:

func provideGinEngine() *gin.Engine {
	return gin.Default()
}
